// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAvBVxabVL6fl9kANtQejaZGz_Q0p2obZU',
    appId: '1:188029078111:android:429a0a91813bf2208469ea',
    messagingSenderId: '188029078111',
    projectId: 'melody-c1456',
    storageBucket: 'melody-c1456.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCZXmE_Skbx9QQ_xp6EIVb59NfDsLsAduU',
    appId: '1:188029078111:ios:0b66b61590ff07b78469ea',
    messagingSenderId: '188029078111',
    projectId: 'melody-c1456',
    storageBucket: 'melody-c1456.firebasestorage.app',
    iosBundleId: 'com.example.melody',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBmpGs8z_4xzU7-dDuC1iaSKoU3nSQG02s',
    appId: '1:188029078111:web:f6ca925866ebd3428469ea',
    messagingSenderId: '188029078111',
    projectId: 'melody-c1456',
    authDomain: 'melody-c1456.firebaseapp.com',
    storageBucket: 'melody-c1456.firebasestorage.app',
    measurementId: 'G-M746Q8C2ME',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCZXmE_Skbx9QQ_xp6EIVb59NfDsLsAduU',
    appId: '1:188029078111:ios:0b66b61590ff07b78469ea',
    messagingSenderId: '188029078111',
    projectId: 'melody-c1456',
    storageBucket: 'melody-c1456.firebasestorage.app',
    iosBundleId: 'com.example.melody',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBmpGs8z_4xzU7-dDuC1iaSKoU3nSQG02s',
    appId: '1:188029078111:web:764fca4adcf1c7928469ea',
    messagingSenderId: '188029078111',
    projectId: 'melody-c1456',
    authDomain: 'melody-c1456.firebaseapp.com',
    storageBucket: 'melody-c1456.firebasestorage.app',
    measurementId: 'G-ER01WQ4EHX',
  );

}